language: node_js
version: 1.0
node_js:
  - "10"
script:
  - yarn install
  - yarn run lint
  - yarn run test
deploy:
  provider: npm
  edge: true
  email: api@shutterstock.com
  api_key: $SSTK_NPM_TOKEN
  on:
    tags: true
